export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_COURSE_BY_ID = 'GET_COURSE_BY_ID';
export const ADD_COURSE_TO_LIST = 'ADD_COURSE_TO_LIST';
export const ADD_COURSE_TO_LIST_SUCCESSED = 'ADD_COURSE_TO_LIST_SUCCESSED';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const REDIRECT = 'REDIRECT';